# Generated by Django 5.1.4 on 2026-04-27 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(choices=[('WEIGHT_LOSS', 'Pérdida de peso'), ('WEIGHT_GAIN', 'Aumento de peso'), ('MAINTENANCE', 'Mantenimiento'), ('MUSCLE_GAIN', 'Ganancia muscular'), ('DIABETES_CTRL', 'Control de diabetes'), ('HEART_HEALTH', 'Salud cardiovascular'), ('CUSTOM', 'Personalizado')], default='MAINTENANCE', max_length=20)),
                ('target_kcal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('target_carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('target_fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('target_fiber_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('target_sodium_mg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_days', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Desayuno'), ('MID_MORNING', 'Media mañana'), ('LUNCH', 'Comida'), ('AFTERNOON', 'Merienda'), ('DINNER', 'Cena'), ('SNACK', 'Colación')], max_length=15)),
                ('day_number', models.PositiveSmallIntegerField(default=1, help_text='Day within the plan cycle (1 = Monday or Day 1).')),
                ('name', models.CharField(help_text='e.g. "Avena con frutas"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kcal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='nutrition.nutritionplan')),
            ],
            options={
                'ordering': ['day_number', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_assignments_sent', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_assignments', to='accounts.patientprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='nutrition.nutritionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_at', models.DateTimeField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Desayuno'), ('MID_MORNING', 'Media mañana'), ('LUNCH', 'Comida'), ('AFTERNOON', 'Merienda'), ('DINNER', 'Cena'), ('SNACK', 'Colación')], max_length=15)),
                ('food_name', models.CharField(max_length=255)),
                ('quantity_g', models.DecimalField(decimal_places=1, help_text='Quantity in grams (or ml for liquids).', max_digits=7)),
                ('kcal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('sodium_mg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='accounts.patientprofile')),
                ('meal_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_entries', to='nutrition.mealslot')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['patient', '-logged_at'], name='nutrition_f_patient_0b714e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyNutritionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_kcal', models.PositiveSmallIntegerField(default=0)),
                ('total_protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('total_carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('total_fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('total_fiber_g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('total_sodium_mg', models.PositiveSmallIntegerField(default=0)),
                ('entry_count', models.PositiveSmallIntegerField(default=0)),
                ('kcal_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kcal_pct', models.DecimalField(blank=True, decimal_places=1, help_text='total_kcal / kcal_target * 100', max_digits=5, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_nutrition_summaries', to='accounts.patientprofile')),
                ('plan_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='nutrition.nutritionplanassignment')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
