# Generated by Django 5.1.4 on 2026-04-27 02:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_name', models.CharField(blank=True, max_length=100)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Desayuno'), ('LUNCH', 'Comida'), ('DINNER', 'Cena'), ('SNACK', 'Colación')], max_length=20)),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_schedules', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'medications_meal_schedule',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('active_compound', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'medications_medication',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('CUSTOM', 'Personalizado'), ('SPECIFIC_DAYS', 'Días específicos')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('repeat_every_days', models.PositiveIntegerField(blank=True, null=True)),
                ('repeat_for_days', models.PositiveIntegerField(blank=True, null=True)),
                ('specific_days_of_week', models.JSONField(blank=True, default=list)),
                ('pause_start_date', models.DateField(blank=True, null=True)),
                ('pause_end_date', models.DateField(blank=True, null=True)),
                ('pause_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('pause_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='medications.medication')),
            ],
            options={
                'db_table': 'medications_pattern',
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('is_relative_to_meal', models.BooleanField(default=False)),
                ('meal_type', models.CharField(blank=True, choices=[('BREAKFAST', 'Desayuno'), ('LUNCH', 'Comida'), ('DINNER', 'Cena'), ('SNACK', 'Colación')], max_length=20)),
                ('offset_minutes', models.IntegerField(default=0)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='medications.medicationpattern')),
            ],
            options={
                'db_table': 'medications_schedule',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('actual_taken_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('TAKEN', 'Tomado'), ('SKIPPED', 'Omitido'), ('POSTPONED', 'Pospuesto')], default='PENDING', max_length=20)),
                ('dosage_taken', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_history', to='accounts.patientprofile')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medicationschedule')),
            ],
            options={
                'db_table': 'medications_history',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['patient', '-scheduled_at'], name='medications_patient_2a34d2_idx'), models.Index(fields=['status', 'scheduled_at'], name='medications_status_dbbf9b_idx')],
            },
        ),
    ]
