# Generated by Django 5.1.4 on 2026-04-27 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rfc', models.CharField(blank=True, help_text='RFC (Mexico tax ID)', max_length=13)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True, max_length=512)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=10)),
                ('agreement_start', models.DateField(blank=True, null=True)),
                ('agreement_end', models.DateField(blank=True, null=True)),
                ('max_members', models.PositiveIntegerField(default=100)),
                ('monthly_fee_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_doctors', models.ManyToManyField(blank=True, related_name='partner_organizations', to='accounts.doctorprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('consenting_members', models.PositiveIntegerField(default=0)),
                ('active_members', models.PositiveIntegerField(default=0, help_text='Members with ≥1 activity this week')),
                ('avg_adherence_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('low_adherence_count', models.PositiveIntegerField(default=0, help_text='Members with adherence < 70%')),
                ('avg_vitals', models.JSONField(blank=True, default=dict, help_text='{"GLUCOSE": 98.2, "WEIGHT": 72.1, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='partners.partnerorganization')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('organization', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='PartnerAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for billing/support')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_roles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='partners.partnerorganization')),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MemberEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=64)),
                ('consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_enrollments', to='accounts.patientprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='partners.partnerorganization')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('organization', 'patient')},
            },
        ),
    ]
