# Generated by Django 5.1.4 on 2026-04-27 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('MENTAL_HEALTH', 'Salud mental'), ('STRESS', 'Manejo del estrés'), ('SLEEP', 'Calidad del sueño'), ('EXERCISE', 'Actividad física'), ('MINDFULNESS', 'Mindfulness'), ('CHRONIC', 'Condición crónica'), ('CUSTOM', 'Personalizado')], default='CUSTOM', max_length=20)),
                ('duration_days', models.PositiveSmallIntegerField(default=21, help_text='Total program length in days.')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wellness_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio / Meditación guiada'), ('ARTICLE', 'Artículo'), ('EXERCISE', 'Ejercicio'), ('BREATHING', 'Respiración'), ('JOURNALING', 'Diario reflexivo'), ('QUIZ', 'Cuestionario')], max_length=15)),
                ('content_url', models.URLField(blank=True, help_text='Link to video/audio/article.')),
                ('body', models.TextField(blank=True, help_text='Inline text content if no URL.')),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, help_text='Estimated minutes to complete.', null=True)),
                ('points_reward', models.PositiveSmallIntegerField(default=0, help_text='Points awarded via gamification on completion.')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='wellness.wellnessprogram')),
            ],
            options={
                'ordering': ['day_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Completado'), ('ABANDONED', 'Abandonado')], db_index=True, default='ACTIVE', max_length=10)),
                ('start_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellness_enrollments_sent', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_enrollments', to='accounts.patientprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='wellness.wellnessprogram')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('program', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('mood_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mood_label', models.CharField(blank=True, choices=[('EXCELLENT', 'Excelente'), ('GOOD', 'Bien'), ('NEUTRAL', 'Neutral'), ('LOW', 'Bajo'), ('ANXIOUS', 'Ansioso/a'), ('STRESSED', 'Estresado/a'), ('SAD', 'Triste'), ('ANGRY', 'Enojado/a')], max_length=15)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('GREAT', 'Excelente'), ('GOOD', 'Buena'), ('FAIR', 'Regular'), ('POOR', 'Mala'), ('INSOMNIA', 'Insomnio')], max_length=10)),
                ('activities_completed', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_at', models.DateTimeField()),
                ('score', models.PositiveSmallIntegerField(help_text='1 (very low) to 10 (excellent).')),
                ('label', models.CharField(blank=True, choices=[('EXCELLENT', 'Excelente'), ('GOOD', 'Bien'), ('NEUTRAL', 'Neutral'), ('LOW', 'Bajo'), ('ANXIOUS', 'Ansioso/a'), ('STRESSED', 'Estresado/a'), ('SAD', 'Triste'), ('ANGRY', 'Enojado/a')], max_length=15)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['patient', '-logged_at'], name='wellness_mo_patient_bffc48_idx')],
            },
        ),
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleep_date', models.DateField(help_text='The date the patient went to sleep.')),
                ('bedtime', models.TimeField(blank=True, null=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Total sleep hours (e.g. 7.5).', max_digits=4)),
                ('quality', models.CharField(choices=[('GREAT', 'Excelente'), ('GOOD', 'Buena'), ('FAIR', 'Regular'), ('POOR', 'Mala'), ('INSOMNIA', 'Insomnio')], default='FAIR', max_length=10)),
                ('interruptions', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_entries', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-sleep_date'],
                'indexes': [models.Index(fields=['patient', '-sleep_date'], name='wellness_sl_patient_b453c5_idx')],
                'unique_together': {('patient', 'sleep_date')},
            },
        ),
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='wellness.programenrollment')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='wellness.wellnessactivity')),
            ],
            options={
                'unique_together': {('enrollment', 'activity')},
            },
        ),
    ]
