# Generated by Django 5.1.4 on 2026-04-27 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, help_text='Role snapshot at the time of action', max_length=20)),
                ('actor_email', models.EmailField(blank=True, help_text='Email snapshot (persists after user deletion)', max_length=254)),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREATE', 'Creación'), ('READ', 'Lectura'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('MEDICATION_TAKEN', 'Medicamento tomado'), ('MEDICATION_SKIPPED', 'Medicamento omitido'), ('LAB_UPLOADED', 'Lab subido'), ('DOCUMENT_SHARED', 'Documento compartido'), ('DOCUMENT_REVOKED', 'Acceso revocado'), ('EXPORT_PDF', 'Exportación PDF'), ('INSIGHT_GENERATED', 'Insight generado'), ('PERMISSION_CHANGE', 'Cambio de permisos'), ('PLAN_CHANGE', 'Cambio de plan'), ('ACCESS_DENIED', 'Acceso denegado'), ('TOKEN_REVOKED', 'Token revocado')], max_length=25)),
                ('resource_type', models.CharField(choices=[('USER', 'Usuario'), ('PATIENT', 'Paciente'), ('DOCTOR', 'Doctor'), ('MEDICATION', 'Medicamento'), ('MEDICATION_HISTORY', 'Historial medicamento'), ('VITAL_SIGN', 'Signo vital'), ('LAB_RESULT', 'Resultado lab'), ('LAB_PANEL', 'Panel lab'), ('APPOINTMENT', 'Cita'), ('DOCUMENT', 'Documento'), ('CHAT', 'Chat'), ('SUBSCRIPTION', 'Suscripción'), ('INSIGHT', 'Insight'), ('EXPORT', 'Exportación'), ('OTHER', 'Otro')], default='OTHER', max_length=25)),
                ('resource_id', models.CharField(blank=True, help_text='UUID or PK of the affected object', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, help_text='HTTP method + path, e.g. POST /api/v1/medications/', max_length=255)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list, help_text='List of field names that changed')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['patient', 'created_at'], name='audit_audit_patient_cf8448_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx')],
            },
        ),
    ]
