# Generated by Django 5.1.4 on 2026-04-27 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], max_length=10)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('total_doses', models.PositiveIntegerField(default=0)),
                ('taken_doses', models.PositiveIntegerField(default=0)),
                ('skipped_doses', models.PositiveIntegerField(default=0)),
                ('postponed_doses', models.PositiveIntegerField(default=0)),
                ('adherence_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('medications_tracked', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_reports', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'analytics_adherence_report',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'period', 'period_start'), name='unique_adherence_report')],
            },
        ),
        migrations.CreateModel(
            name='HealthInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('MEDICATION_ADHERENCE', 'Adherencia a medicamentos'), ('VITAL_TREND', 'Tendencia de vitales'), ('LAB_ANALYSIS', 'Análisis de laboratorio'), ('GENERAL_HEALTH', 'Salud general')], max_length=25)),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic (Claude)'), ('RULE_BASED', 'Reglas')], max_length=15)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('actions', models.JSONField(default=list)),
                ('context_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insights', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'analytics_health_insight',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'insight_type', '-created_at'], name='analytics_h_patient_40e7d8_idx')],
            },
        ),
    ]
