# Generated by Django 5.1.4 on 2026-04-27 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Machine-readable key, e.g. STREAK_7', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ADHERENCE', 'Adherencia'), ('VITALS', 'Signos vitales'), ('STREAK', 'Rachas'), ('SOCIAL', 'Social'), ('MILESTONE', 'Hito')], max_length=12)),
                ('icon_url', models.URLField(blank=True, max_length=512)),
                ('threshold', models.PositiveIntegerField(default=1, help_text='e.g. 7 for STREAK_7 (7-day streak)')),
                ('points_reward', models.PositiveIntegerField(default=0, help_text='Bonus points awarded on unlock')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('MEDICATION_TAKEN', 'Medicamento tomado'), ('VITAL_LOGGED', 'Signo vital registrado'), ('LAB_UPLOADED', 'Resultado lab subido'), ('APPOINTMENT_KEPT', 'Cita completada'), ('STREAK_BONUS', 'Bonus por racha'), ('REFERRAL_COMPLETED', 'Referido completado'), ('PROFILE_COMPLETED', 'Perfil completado'), ('MANUAL_ADJUSTMENT', 'Ajuste manual (admin)')], max_length=22)),
                ('base_points', models.IntegerField(help_text='Points before multiplier')),
                ('multiplier', models.PositiveSmallIntegerField(default=1)),
                ('points', models.IntegerField(help_text='Final points (base × multiplier)')),
                ('ref_id', models.CharField(blank=True, help_text='UUID of the triggering object', max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gamification.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_badges', to='gamification.badge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='gamification.playerprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('player', 'badge')},
            },
        ),
    ]
