# Generated by Django 5.1.4 on 2026-07-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_rewardproduct'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('ref_id', ''), _negated=True), fields=('player', 'source', 'ref_id'), name='unique_points_per_event'),
        ),
    ]
