# Generated by Django 5.1.4 on 2026-07-07 09:03

import apps.gamification.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_pointtransaction_unique_points_per_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.PositiveIntegerField(help_text='Puntos debitados en el canje.')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('FULFILLED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=9)),
                ('code', models.CharField(default=apps.gamification.models.generate_redemption_code, help_text='Código único de canje (ej. RDM-7F3A9C2B).', max_length=12, unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='gamification.playerprofile')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='gamification.rewardproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
