# Generated by Django 5.1.4 on 2026-07-08 05:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_balance(apps, schema_editor):
    """
    Antes de existir el flujo de canje, todo lo ganado estaba sin gastar, así que
    el saldo inicial de cada jugador debe igualar su total_points acumulado.
    """
    PlayerProfile = apps.get_model('gamification', 'PlayerProfile')
    PlayerProfile.objects.update(balance=models.F('total_points'))


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_redemptionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='balance',
            field=models.PositiveIntegerField(default=0, help_text='Puntos disponibles para canjear (ganados − canjeados).'),
        ),
        migrations.RunPython(backfill_balance, migrations.RunPython.noop),
        migrations.AddField(
            model_name='redemptionrecord',
            name='point_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption', to='gamification.pointtransaction'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='source',
            field=models.CharField(choices=[('MEDICATION_TAKEN', 'Medicamento tomado'), ('VITAL_LOGGED', 'Signo vital registrado'), ('LAB_UPLOADED', 'Resultado lab subido'), ('APPOINTMENT_KEPT', 'Cita completada'), ('STREAK_BONUS', 'Bonus por racha'), ('REFERRAL_COMPLETED', 'Referido completado'), ('PROFILE_COMPLETED', 'Perfil completado'), ('MANUAL_ADJUSTMENT', 'Ajuste manual (admin)'), ('REDEMPTION', 'Canje de recompensa')], max_length=22),
        ),
    ]
