# Generated by Django 5.1.4 on 2026-04-27 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('TEAMS', 'Microsoft Teams'), ('WHEREBY', 'Whereby'), ('OTHER', 'Otro')], default='ZOOM', max_length=10)),
                ('meeting_url', models.URLField(blank=True, max_length=1024)),
                ('meeting_id', models.CharField(blank=True, max_length=128)),
                ('meeting_password', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('WAITING', 'Paciente en sala de espera'), ('IN_PROGRESS', 'En curso'), ('COMPLETED', 'Finalizada'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'Paciente no se presentó')], default='SCHEDULED', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('checklist_completed', models.BooleanField(default=False)),
                ('tech_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_session', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(blank=True, help_text='Motivo de consulta / síntomas')),
                ('objective', models.TextField(blank=True, help_text='Hallazgos clínicos observados')),
                ('assessment', models.TextField(blank=True, help_text='Diagnóstico / impresión clínica')),
                ('plan', models.TextField(blank=True, help_text='Plan de tratamiento')),
                ('follow_up_days', models.PositiveSmallIntegerField(blank=True, help_text='Días hasta próxima cita', null=True)),
                ('prescriptions_issued', models.BooleanField(default=False)),
                ('referrals_made', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='telemedicine.videosession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('pre_vitals', models.JSONField(blank=True, default=dict, help_text='{"heart_rate": 72, "blood_pressure": "120/80"}')),
                ('device_info', models.CharField(blank=True, help_text='Browser / OS for tech support', max_length=255)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='telemedicine.videosession')),
            ],
        ),
    ]
