# Generated by Django 5.1.4 on 2026-04-27 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialist_type', models.CharField(choices=[('DOCTOR', 'Médico especialista'), ('LAB', 'Laboratorio'), ('CLINIC', 'Clínica'), ('PHARMACY', 'Farmacia'), ('OTHER', 'Otro')], default='DOCTOR', max_length=10)),
                ('specialty_area', models.CharField(choices=[('CARDIOLOGY', 'Cardiología'), ('ENDOCRINOLOGY', 'Endocrinología'), ('NEUROLOGY', 'Neurología'), ('DERMATOLOGY', 'Dermatología'), ('GYNECOLOGY', 'Ginecología'), ('PEDIATRICS', 'Pediatría'), ('PSYCHIATRY', 'Psiquiatría'), ('ORTHOPEDICS', 'Ortopedia'), ('OPHTHALMOLOGY', 'Oftalmología'), ('NUTRITION', 'Nutrición'), ('LABORATORY', 'Laboratorio clínico'), ('IMAGING', 'Imagen diagnóstica (Rayos X / MRI)'), ('CLINIC', 'Clínica general'), ('PHARMACY', 'Farmacia'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('name', models.CharField(help_text='Full name or institution name', max_length=255)),
                ('license_number', models.CharField(blank=True, help_text='Cédula profesional / registro sanitario', max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, max_length=512)),
                ('consultation_fee_mxn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('languages', models.JSONField(blank=True, default=list, help_text='["es", "en"]')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pendiente de verificación'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camsa_specialist_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_specialists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado por especialista'), ('COMPLETED', 'Consulta realizada'), ('CANCELLED', 'Cancelado'), ('REJECTED', 'Rechazado por especialista')], default='PENDING', max_length=10)),
                ('reason', models.TextField(help_text='Clinical reason for the referral')),
                ('urgency', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('specialist_notes', models.TextField(blank=True)),
                ('patient_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='accounts.patientprofile')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='specialists.specialistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 stars')),
                ('comment', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_reviews', to='accounts.patientprofile')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='specialists.referralrequest')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='specialists.specialistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.doctorprofile')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='specialists.specialistprofile')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['specialty_area', 'is_active'], name='specialists_special_676029_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['specialist_type', 'is_active'], name='specialists_special_67e045_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['verification_status'], name='specialists_verific_e799c7_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrequest',
            index=models.Index(fields=['doctor', 'status'], name='specialists_doctor__1559c7_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrequest',
            index=models.Index(fields=['patient', 'status'], name='specialists_patient_d1d7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrequest',
            index=models.Index(fields=['specialist', 'status'], name='specialists_special_9462a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('doctor', 'specialist')},
        ),
    ]
