# Generated by Django 5.1.4 on 2026-04-27 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('MANUAL', 'Subida manualmente por paciente'), ('MAILYSOFT', 'Recibida desde MailySoft')], default='MANUAL', max_length=12)),
                ('file_url', models.URLField(blank=True, max_length=1024)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Low-res preview for list views', max_length=1024)),
                ('title', models.CharField(blank=True, help_text='Patient-assigned label, e.g. "Receta cardiólogo Feb 2026"', max_length=255)),
                ('prescribed_by', models.CharField(blank=True, help_text='Doctor name as written on the prescription', max_length=255)),
                ('clinic_name', models.CharField(blank=True, max_length=255)),
                ('prescribed_at', models.DateField(blank=True, help_text='Date printed on the prescription', null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Vigente'), ('EXPIRED', 'Vencida'), ('USED', 'Utilizada'), ('UNKNOWN', 'Sin verificar')], default='UNKNOWN', max_length=10)),
                ('medications_listed', models.JSONField(blank=True, default=list)),
                ('mailysoft_id', models.CharField(blank=True, help_text='MailySoft prescription UUID (null for MANUAL)', max_length=128, null=True, unique=True)),
                ('mailysoft_doctor_id', models.CharField(blank=True, help_text='MailySoft doctor UUID who issued it', max_length=128)),
                ('mailysoft_clinic_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-prescribed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('verification_url', models.URLField(blank=True, help_text='Full public URL for QR scan', max_length=1024)),
                ('issued_by_name', models.CharField(blank=True, max_length=255)),
                ('issued_by_license', models.CharField(blank=True, help_text='Professional license number', max_length=128)),
                ('clinic_name', models.CharField(blank=True, max_length=255)),
                ('signature', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='Set if MailySoft revokes the prescription', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='prescriptions.prescription')),
            ],
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_283c70_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'created_at'], name='prescriptio_patient_5ea7b1_idx'),
        ),
    ]
