# Generated by Django 5.1.4 on 2026-04-27 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Uppercase alphanumeric, e.g. BIENVENIDO20', max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Porcentaje (%)'), ('FIXED', 'Monto fijo (MXN)')], max_length=8)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='% or MXN amount', max_digits=8)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('max_uses_per_user', models.PositiveSmallIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False)),
                ('allowed_plans', models.JSONField(blank=True, default=list, help_text='["SILVER","GOLD"] — empty = all plans')),
                ('first_time_only', models.BooleanField(default=False, help_text='Only for users with no prior paid subscription')),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='Stripe coupon ID', max_length=128)),
                ('stripe_promotion_id', models.CharField(blank=True, help_text='Stripe promotion code ID (for Checkout)', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(max_length=8)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_session_id', models.CharField(blank=True, max_length=128)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=128)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
