# Generated by Django 5.1.4 on 2026-04-27 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_device_token',
                'constraints': [models.UniqueConstraint(fields=('user', 'token'), name='unique_user_token')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('MEDICATION_REMINDER', 'Recordatorio de medicamento'), ('MEDICATION_LOW_ADHERENCE', 'Baja adherencia'), ('APPOINTMENT_CONFIRMED', 'Cita confirmada'), ('APPOINTMENT_REMINDER_24H', 'Recordatorio 24h'), ('APPOINTMENT_REMINDER_1H', 'Recordatorio 1h'), ('APPOINTMENT_CANCELLED', 'Cita cancelada'), ('APPOINTMENT_RESCHEDULED', 'Cita reagendada'), ('VITAL_ABNORMAL', 'Vital fuera de rango'), ('LAB_RESULT_ABNORMAL', 'Resultado anormal'), ('DOCTOR_MESSAGE', 'Mensaje del doctor'), ('PRESCRIPTION_RECEIVED', 'Receta recibida'), ('BADGE_EARNED', 'Badge desbloqueado'), ('PARTNER_ENROLLED', 'Alta en programa corporativo'), ('VIDEO_SESSION_READY', 'Sesión de video lista'), ('PATIENT_WAITING', 'Paciente en sala de espera'), ('REFERRAL_RECEIVED', 'Referido recibido'), ('REFERRAL_STATUS_CHANGED', 'Estado de referido actualizado'), ('PAYMENT_FAILED', 'Pago fallido'), ('SURVEY_ASSIGNED', 'Nueva encuesta asignada'), ('SURVEY_COMPLETED', 'Encuesta completada'), ('NUTRITION_PLAN_ASSIGNED', 'Plan nutricional asignado'), ('WELLNESS_PROGRAM_ENROLLED', 'Inscripción a programa de bienestar'), ('WELLNESS_PROGRAM_COMPLETED', 'Programa de bienestar completado'), ('WELCOME', 'Bienvenida')], db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email'), ('IN_APP', 'In-App')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviada'), ('FAILED', 'Fallida'), ('READ', 'Leída')], db_index=True, default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='notificatio_user_id_eebdc7_idx')],
            },
        ),
    ]
