# Generated by Django 5.1.4 on 2026-04-27 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vital_type', models.CharField(choices=[('BLOOD_PRESSURE', 'Presión arterial'), ('HEART_RATE', 'Frecuencia cardíaca'), ('OXYGEN_SAT', 'Saturación O₂'), ('RESPIRATORY', 'Frecuencia respiratoria'), ('GLUCOSE', 'Glucosa'), ('GLUCOSE_FAST', 'Glucosa en ayuno'), ('WEIGHT', 'Peso'), ('HEIGHT', 'Talla'), ('BMI', 'Índice de masa corporal'), ('WAIST', 'Perímetro de cintura'), ('HIP', 'Perímetro de cadera'), ('TEMPERATURE', 'Temperatura corporal'), ('STEPS', 'Pasos'), ('SLEEP_HOURS', 'Horas de sueño')], max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_secondary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_secondary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_goals', to='accounts.patientprofile')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_goals_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vitals_goal',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'vital_type'), name='unique_active_goal_per_vital')],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vital_type', models.CharField(choices=[('BLOOD_PRESSURE', 'Presión arterial'), ('HEART_RATE', 'Frecuencia cardíaca'), ('OXYGEN_SAT', 'Saturación O₂'), ('RESPIRATORY', 'Frecuencia respiratoria'), ('GLUCOSE', 'Glucosa'), ('GLUCOSE_FAST', 'Glucosa en ayuno'), ('WEIGHT', 'Peso'), ('HEIGHT', 'Talla'), ('BMI', 'Índice de masa corporal'), ('WAIST', 'Perímetro de cintura'), ('HIP', 'Perímetro de cadera'), ('TEMPERATURE', 'Temperatura corporal'), ('STEPS', 'Pasos'), ('SLEEP_HOURS', 'Horas de sueño')], db_index=True, max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('secondary_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('DEVICE', 'Dispositivo'), ('INTEGRATION', 'Integración')], default='MANUAL', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'vitals_vital_sign',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'vital_type', '-recorded_at'], name='vitals_vita_patient_b9d253_idx'), models.Index(fields=['patient', '-recorded_at'], name='vitals_vita_patient_80cbb8_idx')],
            },
        ),
    ]
